### ISSUE TITLE
Implement [Home Page (screen 1) MOBILE]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#103]
![image](https://user-images.githubusercontent.com/58891908/179309615-9b40c172-d3ef-48e3-82fc-4df02c99642f.png)

**Comment by dpkreativ** [comment]
Hi! Please I'd like to work on this
Slack: **Divi**

**Comment by toluolatubosun** [comment]
@dpkreativ you have been assigned this issue 🚀🚀

**Comment by dpkreativ** [comment]
Hi @toluolatubosun 
Can you kindly assign someone else to this issue? I don't think I'll have time to work on it and it has really stayed too long in my hands. 
Thanks

**Comment by kodervine** [comment]
I'd like to work on this
@laskelly
