### ISSUE TITLE
Implement Mobile Authentication Pages [screen 1] 

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#117]
![image](https://user-images.githubusercontent.com/58891908/180064088-902bef0f-64d1-41b4-9dce-43bde76b1ec5.png)

**Comment by kodervine** [comment]
I'd love to work on this
@laskelly

**Comment by code-art4** [comment]
Isn't this responsive already?

**Comment by toluolatubosun** [comment]
@laskelly you have been assigned this issue 🚀🚀
