### ISSUE TITLE
Implement Mobile Authentication Page [screen 2] 

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#118]
![image](https://user-images.githubusercontent.com/58891908/180065048-52e698cf-af69-4f73-9116-b09398e44926.png)

**Comment by Dubjay18** [comment]
I'll like to work on this @Dub_jay

**Comment by toluolatubosun** [comment]
@Dubjay18 you have been assigned this issue 🚀🚀
