### ISSUE TITLE
Implement the profile_sidecard component

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#12]
![image](https://user-images.githubusercontent.com/58891908/173916705-eb23d98f-e4d8-4090-bb9e-d8721bc2bd46.png)

**Comment by Sandee004** [comment]
I'd like to take this
@Sandee

**Comment by calebareeveso** [comment]
@Sandee004  this issue has been assigned to you. 

We would be be expecting this before our check up call on Saturday. We are counting on you.

Thanks.
