### ISSUE TITLE
Implement [Forgot Password Page Process (screen 4)] completed

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#122]
![image](https://user-images.githubusercontent.com/58891908/180065970-2fb6f086-f1a1-4198-b99e-c36e97aa5ab1.png)

**Comment by jaypee-0** [comment]
I could go on this too
 @Jaypee

**Comment by toluolatubosun** [comment]
@jaypee-0 you have been assigned this issue 🚀🚀

**Comment by jaypee-0** [comment]
Alright
