### ISSUE TITLE
Implement Mobile [Search (screen 1)]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#124]
![image](https://user-images.githubusercontent.com/58891908/180070559-75484efb-0309-450b-9ba4-b36b2f435c3b.png)

**Comment by kodervine** [comment]
xx

**Comment by OcheOps** [comment]
Its cool

**Comment by tochibedford** [comment]
slack @tochi

**Comment by toluolatubosun** [comment]
@tochibedford you have been assigned this issue 🚀🚀
