### ISSUE TITLE
Implement Mobile Creating a  post [screen (2)]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#125]
![image](https://user-images.githubusercontent.com/58891908/180069846-df9c478d-747c-4b30-83b4-18827a6ee08e.png)

**Comment by code-art4** [comment]
I'm interested in taking this task @code-art4

**Comment by toluolatubosun** [comment]
@code-art4 you have been assigned this issue 🚀🚀

**Comment by kodervine** [comment]
I'd like to work on this
@laskelly
