### ISSUE TITLE
Fix Home page / recent / Latest News page

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#126]
![image](https://user-images.githubusercontent.com/58891908/180072663-0c1c8ca8-8bfe-4353-bf62-c4f07a76a063.png)

**Comment by d-a-ve** [comment]
I will like to work on this.
Slack: Dave.

**Comment by toluolatubosun** [comment]
@d-a-ve you have been assigned this issue 🚀🚀
