### ISSUE TITLE
Implement [Reading a post Mobile (screen5)]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#127]
![image](https://user-images.githubusercontent.com/58891908/180072986-be1baf50-7c2d-4701-9c90-ef73aa847732.png)

**Comment by Dideoluwa** [comment]
I'll take this 
Slack: @Dideoluwa

**Comment by toluolatubosun** [comment]
@Dideoluwa you have been assigned this issue

**Comment by toluolatubosun** [comment]
🚀🚀
