### ISSUE TITLE
implement the navbar component

### ISSUE THREAD

**Issue by eni4sure** [GenZTechies/Nairaland#2]
![image](https://user-images.githubusercontent.com/58891908/174673105-dbed1f24-d7fb-4894-80a2-39b4093e8957.png)

**Comment by Emmauel98** [comment]
I will like to take this.
Slack: @oluwapelumi

**Comment by Kodedbykenzie** [comment]
I will to work on this
slack: Mozia Precious

**Comment by calebareeveso** [comment]
@Emmauel98  this issue has been assigned to you. 

We would be be expecting this before our check up call on Saturday. We are counting on you.

Thanks.

**Comment by 0xsherifdev** [comment]
Commenting...

**Comment by dpkreativ** [comment]
Hi. I'd like to take this issue
Slack: @Divi

**Comment by Divi** [comment]
Hello @dpkreativ 👋🏻 
I guess you use a bot to ping your buddy on your Slack, but actually, I'm the one you ping so I get some notifications and... I don't know you or this repository 😁 

I'm turning off the notification of this repository, but please consider updating your bot or escaping the mentions like `@Divi`.

Bye!

![](https://c.tenor.com/I6bSd_xNoc0AAAAC/hooray-its-weekend.gif)

**Comment by icemedia001** [comment]
Has this issue been assigned to anyone?

**Comment by jaypee-0** [comment]
If no one is handling this, I would like to handle it
