### ISSUE TITLE
Implement button component 

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#20]
![image](https://user-images.githubusercontent.com/58891908/173959844-0293cc53-da68-4d67-beb6-374d787217b3.png)

**Comment by xOluwaseyi** [comment]
I have picked this up.

**Comment by calebareeveso** [comment]
Alright man, we need this urgently 🤲🏾

**Comment by xOluwaseyi** [comment]
I am done with it, you can review and merge now. 😁.
<img width="960" alt="nairaland#button" src="https://user-images.githubusercontent.com/75592533/173976669-273b5673-b404-43cb-8491-37c95d04d44c.PNG">

**Comment by calebareeveso** [comment]
Great job 🚀

**Comment by xOluwaseyi** [comment]
> Great job 🚀

Yessir 😁
