### ISSUE TITLE
Implement the Fotter component 

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#3]
![image](https://user-images.githubusercontent.com/58891908/173908659-f23964f7-9180-454f-b5ab-1ee67e95d8c4.png)

**Comment by Dubjay18** [comment]
I'll like to take this issue
Slack: @Dub_jay

**Comment by Dideoluwa** [comment]
I want to take this issue 
slack: @Dideoluwa

**Comment by Oluwasemilore1** [comment]
I will love to take this issue!

Slack : @Oluwasemilore

**Comment by calebareeveso** [comment]
@Dubjay18  this issue has been assigned to you. 

We would be be expecting this before our check up call on Saturday. We are counting on you.

Thanks.
