### ISSUE TITLE
Implement Mobile Navbar [SIGNOUT]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#39]
![image](https://user-images.githubusercontent.com/58891908/174668117-e94f6cc0-69a7-4287-b1a6-6933616fc135.png)

**Comment by usmangurowa** [comment]
Hi, I will work on this.
Slack: @Usman Gurowa

**Comment by calebareeveso** [comment]
![image](https://user-images.githubusercontent.com/58891908/174670769-4251fa8e-ad44-4d8e-9e33-1411e96fbe2b.png)

**Comment by calebareeveso** [comment]
@usmangurowa this issue has been to you
