### ISSUE TITLE
Implement the Replies component

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#4]
![image](https://user-images.githubusercontent.com/58891908/173909441-51cfa1f0-f23d-4ae0-866c-dc84704c7b0c.png)

**Comment by dpkreativ** [comment]
Hi @calebareeveso I would like to work on this issue.

Slack: @dpkreativ

**Comment by calebareeveso** [comment]
Couldn't find the tag

**Comment by itz-jherie** [comment]
- @calebareeveso I would like to work in this
Slack: @jherie

**Comment by dpkreativ** [comment]
@calebareeveso sorry the Slack tag is @Divi

**Comment by usmangurowa** [comment]
Hi, I will take this issue. Or work together with @dpkreativ on it.
Slack: @Usman Hassan

**Comment by dpkreativ** [comment]
Hi @usmangurowa have you started work on this yet?

**Comment by calebareeveso** [comment]
@dpkreativ this issue has been assigned to you 🙇🏽‍♂️

**Comment by usmangurowa** [comment]
@dpkreativ no not yet. You can take it if you want, or we can work on it together if you want as well.

**Comment by dpkreativ** [comment]
Okay, thanks @calebareeveso @usmangurowa 

I think I'll do this one alone since it's a small component. Thanks for offering to collabo tho @usmangurowa
