### ISSUE TITLE
Implements frame 512 mobile component

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#42]
Link to PR: https://github.com/GenZTechies/Nairaland/pull/22

**Comment by Dideoluwa** [comment]
I will like to take this 
slack: @dideoluwa

**Comment by calebareeveso** [comment]
@Dideoluwa this PR has been assigned to you.

**Comment by Itzadetunji** [comment]
@calebareeveso can I work on this issue?

**Comment by calebareeveso** [comment]
@Itzadetunji this issue is closed bro. There are more recent issues kindly check them out
