### ISSUE TITLE
I implemented frame 71 mobile

### ISSUE THREAD

**Issue by toluolatubosun** [GenZTechies/Nairaland#43]
https://github.com/GenZTechies/Nairaland/pull/24

**Comment by odelolajosh** [comment]
I will like to take this
slack: joshuuua

**Comment by code-art4** [comment]
I like to do this @code_art4

**Comment by odelolajosh** [comment]
I will like to take this
slack: @joshuuua

**Comment by SanaUdoekong** [comment]
I'd like to take this up
Slack: @sanaudoekong

**Comment by calebareeveso** [comment]
@code-art4 this issue has been assigned to you
