### ISSUE TITLE
Implements Frame 509 mobile

### ISSUE THREAD

**Issue by toluolatubosun** [GenZTechies/Nairaland#44]
Link to PR: https://github.com/GenZTechies/Nairaland/pull/23

![image](https://user-images.githubusercontent.com/58891908/174672824-db630d76-10de-4ff8-97d3-ad71696cc4b7.png)

**Comment by odelolajosh** [comment]
I will like to take this
slack: @Joshuuua

**Comment by code-art4** [comment]
I like to work on this @code_art4

**Comment by Itzadetunji** [comment]
I am gonna work on that
