### ISSUE TITLE
Implement mobile Navbar component [SIGNIN]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#51]
![image](https://user-images.githubusercontent.com/58891908/174675837-a451de96-12ce-4c42-8c4c-b8cecc7e1d54.png)

**Comment by 0xsherifdev** [comment]
@Sherifdeen Adebayo

**Comment by calebareeveso** [comment]
@herdeybayor this issue has been assigned to you

**Comment by Timi-Leyin** [comment]
i'll like to work on this

**Comment by jaypee-0** [comment]
Jaypee wanna take this

**Comment by toluolatubosun** [comment]
@jaypee-0 you have been assigned this issue 🚀🚀
