### ISSUE TITLE
Implement Home Pages /  Flow  | When User is signed out.

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#63]
![image](https://user-images.githubusercontent.com/58891908/175382456-f1856622-1ec6-47f1-b3c1-02875d2aadae.png)

**Comment by icemedia001** [comment]
I'd like to take this issue

**Comment by calebareeveso** [comment]
Kindly add your slack tag

**Comment by icemedia001** [comment]
@ÏÇË

**Comment by toluolatubosun** [comment]
@grhackode  you have assigned to this issue
