### ISSUE TITLE
Implement View Post Pages /  Flow  | When User is signed out.

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#64]
![image](https://user-images.githubusercontent.com/58891908/175382697-7b9d0aed-a22c-4694-a28e-86900ebdd6bb.png)

**Comment by dpkreativ** [comment]
Hi @calebareeveso I would like to work on this issue
Slack: **Divi**

**Comment by toluolatubosun** [comment]
@dpkreativ you have been assigned this issue
