### ISSUE TITLE
Authentication Pages [screen 2]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#70]
![image](https://user-images.githubusercontent.com/58891908/175385865-44509c16-d218-46a5-ae9a-6997010bcc61.png)

**Comment by SanaUdoekong** [comment]
I'd like to work on this
Slack: @ sana

**Comment by usmangurowa** [comment]
@SanaUdoekong we could work on it together if you like.

**Comment by SanaUdoekong** [comment]
@usmangurowa send me a dm on slack @ sana

**Comment by toluolatubosun** [comment]
@SanaUdoekong this has been assigned to you
