### ISSUE TITLE
Implement [Creating a  post Screen]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#92]
![image](https://user-images.githubusercontent.com/58891908/179307565-079ec8f6-20ec-49d6-93e3-615b3b9864cb.png)

**Comment by kodervine** [comment]
I will like to work on this
Slack - @laskelly

**Comment by toluolatubosun** [comment]
@laskelly you have been assigned this issue 🚀🚀

**Comment by rhedwan** [comment]
I would like to work on this @rhedwan

**Comment by kodervine** [comment]
@calebareeveso this task is not done 

Rhedwan hasn't made his pull request yet

**Comment by rhedwan** [comment]
@calebareeveso the implementation is in progress
