### ISSUE TITLE
Implement [Home Pages/recent/trending] in Screen

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#93]
![image](https://user-images.githubusercontent.com/58891908/179303999-9420bca0-cf94-4d03-a97b-fbfcd527fcdb.png)

**Comment by d-a-ve** [comment]
Yeah I want to work on this.
Slack ID: @Dave

**Comment by toluolatubosun** [comment]
@d-a-ve you have been assigned this issue 🚀🚀

**Comment by dave** [comment]
As you can imagine, not the first time 🤣

**Comment by d-a-ve** [comment]
Yeah I am currently working on this, but the page that has been coded is not screen 5, its screen 4. so I cannot change the tag to trending, recent and latest news. What should I do? 

I have started working on screen 1 tho but I just saw that someone has been assigned to that issue already and i do not want to do something that someone is already doing
