### ISSUE TITLE
Implement [Home page(screen 5)] 

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#94]
![image](https://user-images.githubusercontent.com/58891908/179305203-eb7125a1-2a6a-46c4-bd36-7e589d0f07a7.png)

**Comment by Dideoluwa** [comment]
I will like to take this 
slack:@dideoluwa

**Comment by Dideoluwa** [comment]
I will like to take this 
slack:@dideoluwa

**Comment by toluolatubosun** [comment]
@Dideoluwa you have been assigned this task 🚀🚀
