### ISSUE TITLE
Implement [Update your Profile Screen]

### ISSUE THREAD

**Issue by calebareeveso** [GenZTechies/Nairaland#97]
![image](https://user-images.githubusercontent.com/58891908/179306706-b35deaf2-63a2-4813-ba1d-e3efec95d957.png)

**Comment by godwin-morwin** [comment]
Hi @caleb, im Godwin daniel , i do like to work on this issue 

@g.olele

**Comment by toluolatubosun** [comment]
@Godwindaniel10 you have been assigned this issue 🚀🚀

**Comment by Emmauel98** [comment]
@Godwindaniel10 please I can't find you on slack

**Comment by Emmauel98** [comment]
Okay Godwin let's get to work 💪
